---
title: "Annual Calls Report"
author: "Laura Pelayo"
date: "2024-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(dplyr)
library(readr)
library(stringr)
library(lubridate)
```

## Annual Calls Report

Runs on Hotline Calls for Impact Report 2.1

```{r Read Data and initial cleaning}

# age function
age <- function(from, to) {
  from_lt = as.POSIXlt(from)
  to_lt = as.POSIXlt(to)
  age = to_lt$year - from_lt$year
  ifelse(to_lt$mon < from_lt$mon |
           (to_lt$mon == from_lt$mon & to_lt$mday < from_lt$mday),
         age - 1, age)
}


all_data <- "Data/Excel format/Hotline Calls for Impact Report 04.10.24.xlsx"

# Define the start and end of the year 2023
year_start <- ymd("20230101")
year_end <- ymd("20231231")
 
# Adjusted code for hmis_call_data to include date range filter for 2023
hmis_call_data <- read_excel(all_data, sheet = 1) %>%
  `colnames<-`(gsub(" ", "", names(.))) %>%
  mutate(NeedDateAdded = as.Date(NeedDateAdded),
         NeedHouseholdId = gsub(",", "", NeedHouseholdId)) %>%
  filter(NeedDateAdded >= year_start & NeedDateAdded <= year_end, 
         ClientUid != 26860)
 
# Adjusted code for hmis_living_situations to include date range filter for 2023
hmis_living_situations <- read_excel(all_data, sheet = 2) %>%
  `colnames<-`(gsub(" ", "", names(.))) %>%
  mutate(EventDate = as.Date(EventDate)) %>%
  filter(EventDate >= year_start & EventDate <= year_end)
 
# hmis_demographics
hmis_demographics <- read_excel(all_data, sheet = 3) %>%
  `colnames<-`(gsub(" ", "", names(.))) %>%
  mutate(DateofBirth = as.Date(DateofBirth))
 
# Adjusted code for call_data to include date range filter for 2023
call_data <- read_excel(all_data, sheet = 4) %>%
  `colnames<-`(gsub(" ", "", names(.))) %>%
  mutate(CallRecordStartDate = as.Date(CallRecordStartDate),
         DateofBirth = as.Date(DateofBirth)) %>%
  filter(CallRecordStartDate >= year_start & CallRecordStartDate <= year_end, 
         ClientID != 26860 & !is.na(NameString))

cat("Column names for hmis_demographics:\n")
cat(paste(colnames(hmis_demographics), collapse = "\n"), "\n\n") 

# Ensure the date columns are Date objects and print the ranges explicitly formatted
cat("HMIS Call Data Date Range:\n")
cat("Start: ", format(min(hmis_call_data$NeedDateAdded, na.rm = TRUE), "%Y-%m-%d"), 
    "\nEnd: ", format(max(hmis_call_data$NeedDateAdded, na.rm = TRUE), "%Y-%m-%d"), "\n\n")
 
# For HMIS Living Situations
cat("HMIS Living Situations Date Range:\n")
cat("Start: ", format(min(hmis_living_situations$EventDate, na.rm = TRUE), "%Y-%m-%d"), 
    "\nEnd: ", format(max(hmis_living_situations$EventDate, na.rm = TRUE), "%Y-%m-%d"), "\n\n")
 
# For Call Data
cat("Call Data Date Range:\n")
cat("Start: ", format(min(call_data$CallRecordStartDate, na.rm = TRUE), "%Y-%m-%d"), 
    "\nEnd: ", format(max(call_data$CallRecordStartDate, na.rm = TRUE), "%Y-%m-%d"), "\n")

```


```{r process non-CallPoint data}

hmis_caller_data <- hmis_call_data %>%
  left_join(hmis_living_situations, by = c("ClientUid", "NeedDateAdded" = "EventDate")) %>%
  left_join(hmis_demographics, by = "ClientUid") %>%
  mutate(client_requested_shelter = if_else(
    NeedCodeDescription %in% c("Homeless Motel Vouchers", "Emergency Shelter", "Domestic Violence Shelters"), 1, 0),
    Housed_Status = case_when(
           ## identify those that are definitely literally homeless
           NeedCodeDescription == "Coordinated Entry (all literally homeless)" |
             # FleeingDV == "Yes" |
             PriorLivingSituation %in% c("Place not meant for habitation (HUD)",
                                         "Place not meant for habitation (e.g., a vehicle, an abandoned building, bus/train/subway station/airport or anywhere outside) (HUD)", # FY24
                                         "Emergency shelter, incl. hotel/motel paid for w/ ES voucher, or RHY-funded Host Home shelter (HUD)",
                                         "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, Host Home shelter (HUD)", #FY24
                                         "Domestic Violence Situation", "Homeless/on the Street", "Safe Haven (HUD)",
                                         "Transitional housing for homeless persons (including homeless youth) (HUD)")
           ~ "Literally Homeless",
           ## identify those that are definitely housed
           NeedCodeDescription %in% c("Prevention - Available (at-risk of homelessness, may refer)",
                                      "Prevention - Not Available (at-risk of homelessness, no referral possible)",
                                      "Prevention - ERAP (CARES money)",
                                      "Information Only (not literally homeless or at-risk)") |
             PriorLivingSituation %in% c("Foster care home or foster care group home (HUD)",
                                         "Group home (not foster care)",
                                          "Hospital or other residential non-psychiatric medical facility (HUD)",
                                          "Hotel or motel paid for without emergency shelter voucher (HUD)",
                                          "Interim Housing (HUD) (Retired)",
                                          "Jail, prison or juvenile detention facility (HUD)",
                                          "Jail, prison, or juvenile detention facility (HUD)",
                                          "Long-term care facility or nursing home (HUD)",
                                          "Owned by client, no ongoing housing subsidy (HUD)",
                                          "Owned by client, with ongoing housing subsidy (HUD)",
                                          "Permanent housing (other than RRH) for formerly homeless persons (HUD)",
                                          "Psychiatric hospital or other psychiatric facility (HUD)",
                                          "Rental by client in a public housing unit (HUD)",
                                          "Rental by client, no ongoing housing subsidy (HUD)",
                                          "Rental by client, with GPD TIP housing subsidy (HUD)",
                                          "Rental by client, with HCV voucher (tenant or project based) (HUD)",
                                          "Rental by client, with RRH or equivalent subsidy (HUD)",
                                          "Rental by client, with VASH housing subsidy (HUD)",
                                          "Rental by client, with ongoing housing subsidy (HUD)",
                                          "Rental by client, with other ongoing housing subsidy (HUD)",
                                          "Residential project or halfway house with no homeless criteria (HUD)",
                                          "Staying or living in a family member's room, apartment or house (HUD)",
                                          "Staying or living in a family member's room, apartment, or house (HUD)",
                                          "Staying or living in a friend's room, apartment or house (HUD)",
                                          "Staying or living in a friend's room, apartment, or house (HUD)",
                                          "Substance abuse treatment facility or detox center (HUD)")
           ~ "Not Literally Homeless",
           ## identify those that are probably literally homeless
           # NeedCodeDescription %in% c("Housing Related Coordinated Entry", "Emergency Shelter", "Homeless Motel Vouchers",
           #                            "Homeless Safe Parking Programs", "Domestic Violence Shelters",
           #                            ## "Animal Shelters" is an artifact of how some shelter referrals are made
           #                            "Animal Shelters")
           # ~ "Literally Homeless",
           ## identify those that are probably housed
           NeedCodeDescription %in% c("Rent Payment Assistance", "Homelessness Prevention Programs")
           ~ "Not Literally Homeless",
           ## all others are unknown but marked not literal for these purposes
           TRUE ~ "Not Literally Homeless"
         ),
         BIPOC_flag = if_else(
      str_detect(`RaceandEthnicity(3397)`, "American Indian, Alaska Native, or Indigenous") |
      str_detect(`RaceandEthnicity(3397)`, "Asian or Asian American") |
      str_detect(`RaceandEthnicity(3397)`, "Black, African American, or African") |
      str_detect(`RaceandEthnicity(3397)`, "Hispanic/Latina/e/o") |
      str_detect(`RaceandEthnicity(3397)`, "Middle Eastern or North African") |
      str_detect(`RaceandEthnicity(3397)`, "Native Hawaiian or Pacific Islander"),
      1, 
      0
    )
  ) %>%
  select(NeedHouseholdId, ClientUid, NeedDateAdded, ClientVeteranStatus, NameString, DateofBirth, Housed_Status, BIPOC_flag, client_requested_shelter)

# print date range to verify 2023 data
cat("HMIS Caller Data Date Range (NeedDateAdded):\n")
cat("Start: ", format(min(hmis_caller_data$NeedDateAdded, na.rm = TRUE), "%Y-%m-%d"), 
    "\nEnd: ", format(max(hmis_caller_data$NeedDateAdded, na.rm = TRUE), "%Y-%m-%d"), "\n")

```




```{r process CallPoint data}

callpoint_caller_data <- call_data %>%
  mutate(Housed_Status = case_when(
    ## identify those that are definitely literally homeless
    CallRecordCallType == "Coordinated Entry (all literally homeless)" |
      # FleeingDV == "Yes" |
      PriorLivingSituation %in% c("Place not meant for habitation (HUD)",
                                         "Place not meant for habitation (e.g., a vehicle, an abandoned building, bus/train/subway station/airport or anywhere outside) (HUD)", # FY24
                                         "Emergency shelter, incl. hotel/motel paid for w/ ES voucher, or RHY-funded Host Home shelter (HUD)",
                                         "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, Host Home shelter (HUD)", #FY24
                                         "Domestic Violence Situation", "Homeless/on the Street", "Safe Haven (HUD)",
                                         "Transitional housing for homeless persons (including homeless youth) (HUD)")
    ~ "Literally Homeless",
    ## identify those that are definitely housed
    CallRecordCallType %in% c("Prevention - Available (at-risk of homelessness, may refer)",
                               "Prevention - Not Available (at-risk of homelessness, no referral possible)",
                               "Prevention - ERAP (CARES money)",
                               "Information Only (not literally homeless or at-risk)") |
      PriorLivingSituation %in% c("Foster care home or foster care group home (HUD)",
                                         "Group home (not foster care)",
                                          "Hospital or other residential non-psychiatric medical facility (HUD)",
                                          "Hotel or motel paid for without emergency shelter voucher (HUD)",
                                          "Interim Housing (HUD) (Retired)",
                                          "Jail, prison or juvenile detention facility (HUD)",
                                          "Jail, prison, or juvenile detention facility (HUD)",
                                          "Long-term care facility or nursing home (HUD)",
                                          "Owned by client, no ongoing housing subsidy (HUD)",
                                          "Owned by client, with ongoing housing subsidy (HUD)",
                                          "Permanent housing (other than RRH) for formerly homeless persons (HUD)",
                                          "Psychiatric hospital or other psychiatric facility (HUD)",
                                          "Rental by client in a public housing unit (HUD)",
                                          "Rental by client, no ongoing housing subsidy (HUD)",
                                          "Rental by client, with GPD TIP housing subsidy (HUD)",
                                          "Rental by client, with HCV voucher (tenant or project based) (HUD)",
                                          "Rental by client, with RRH or equivalent subsidy (HUD)",
                                          "Rental by client, with VASH housing subsidy (HUD)",
                                          "Rental by client, with ongoing housing subsidy (HUD)",
                                          "Rental by client, with other ongoing housing subsidy (HUD)",
                                          "Residential project or halfway house with no homeless criteria (HUD)",
                                          "Staying or living in a family member's room, apartment or house (HUD)",
                                          "Staying or living in a family member's room, apartment, or house (HUD)",
                                          "Staying or living in a friend's room, apartment or house (HUD)",
                                          "Staying or living in a friend's room, apartment, or house (HUD)",
                                          "Substance abuse treatment facility or detox center (HUD)")
    ~ "Not Literally Homeless",
    ## all others are unknown but marked not literal for these purposes
    TRUE ~ "Not Literally Homeless"
  ),
  BIPOC_flag = if_else(
      str_detect(`RaceandEthnicity(HUD_RACEETHNICITY)`, "American Indian, Alaska Native, or Indigenous") |
      str_detect(`RaceandEthnicity(HUD_RACEETHNICITY)`, "Asian or Asian American") |
      str_detect(`RaceandEthnicity(HUD_RACEETHNICITY)`, "Black, African American, or African") |
      str_detect(`RaceandEthnicity(HUD_RACEETHNICITY)`, "Hispanic/Latina/e/o") |
      str_detect(`RaceandEthnicity(HUD_RACEETHNICITY)`, "Middle Eastern or North African") |
      str_detect(`RaceandEthnicity(HUD_RACEETHNICITY)`, "Native Hawaiian or Pacific Islander"),
      1, 
      0
    )
  ) %>%
  select(ClientID, CallRecordStartDate, VeteranStatus, NameString, DateofBirth, Housed_Status, BIPOC_flag)

# print date range to verify 2023 data
cat("Callpoint Caller Data Date Range (CallRecordStartDate):\n")
cat("Start: ", format(min(callpoint_caller_data$CallRecordStartDate, na.rm = TRUE), "%Y-%m-%d"), 
    "\nEnd: ", format(max(callpoint_caller_data$CallRecordStartDate, na.rm = TRUE), "%Y-%m-%d"), "\n")

```



```{r join data for more processing}

## Join data
all_caller_data <- hmis_caller_data %>%
  full_join(callpoint_caller_data, by = c("ClientUid" = "ClientID", "NeedDateAdded" = "CallRecordStartDate",
                                          "ClientVeteranStatus" = "VeteranStatus", "NameString", "DateofBirth",
                                          "Housed_Status", "BIPOC_flag")) %>%
  group_by(NameString) %>%
  mutate(DateofBirth = if_else(is.na(DateofBirth),
                               max(if_else(is.na(DateofBirth), ymd("18000101"), DateofBirth)),
                               DateofBirth),
         DateofBirth = case_when(DateofBirth != ymd("18000101") ~ DateofBirth)) %>%
  group_by(NameString, DateofBirth) %>%
  ## Resolve any duplicate client IDs
  mutate(HMIS_ClientID = min(if_else(ClientUid > 0, ClientUid, 999999)),
         HMIS_ClientID = case_when(HMIS_ClientID != 999999 ~ HMIS_ClientID),
         First_Call_ClientID = max(ClientUid),
         ClientUid = if_else(is.na(HMIS_ClientID), First_Call_ClientID, HMIS_ClientID)) %>%
  ungroup() %>%
  mutate(NeedHouseholdId = if_else(is.na(NeedHouseholdId), paste0(ClientUid, "-C"), NeedHouseholdId)) %>%
  group_by(ClientUid) %>%
  mutate(veteran = if_else(max(if_else(ClientVeteranStatus == "Yes (HUD)", 1, 0)) == 1, "Yes", "No"),
         BIPOC_flag = max(BIPOC_flag),
         client_requested_shelter = max(case_when(!is.na(client_requested_shelter) ~ client_requested_shelter,
                                                  TRUE ~ 0)),
         Age = age(DateofBirth, NeedDateAdded)) %>%
  ungroup() %>%
  ## Adjusted to ensure NameString is not excluded
  select(-c(ClientVeteranStatus, HMIS_ClientID, First_Call_ClientID))
 
## Perform checks and summarization
check <- all_caller_data %>%
  select(NameString, DateofBirth, Housed_Status) %>%
  distinct() %>%
  group_by(Housed_Status) %>%
  summarise(count = n())

# print date range to verify 2023 data
cat("All Caller Data Date Range (NeedDateAdded):\n")
cat("Start: ", format(min(all_caller_data$NeedDateAdded, na.rm = TRUE), "%Y-%m-%d"), 
    "\nEnd: ", format(max(all_caller_data$NeedDateAdded, na.rm = TRUE), "%Y-%m-%d"), "\n")

```



```{r prepare table for summarizing}

for_summary <- all_caller_data %>%
  select(-NeedDateAdded) %>%
  distinct() %>%
  group_by(NeedHouseholdId, Housed_Status) %>%
  mutate(household_size = n()) %>%
  ungroup() %>%
  group_by(NeedHouseholdId) %>%
  mutate(max_age = max(if_else(is.na(Age), -99, Age)),
         max_age = case_when(max_age != -99 ~ max_age),
         min_age = min(if_else(is.na(Age), 99, Age)),
         min_age = case_when(min_age != 99 ~ min_age),
         client_requested_shelter = case_when(client_requested_shelter == 1 ~ "Yes",
                                              TRUE ~ "No")
         # , Housed_Status = factor(Housed_Status,
         #                        levels = c("Literally Homeless", "Not Literally Homeless", "Unknown"))) %>%
         #                        levels = c("Not Literally Homeless", "Literally Homeless", "Unknown"))
         ) %>%
  arrange(desc(household_size), Housed_Status) %>%
  ungroup() %>%
  group_by(ClientUid) %>%
  slice(1L) %>%
  ungroup()

```


```{r set up summary calculations}

hotline_summary_numbers <- function(df, title)
{
  all_calling <- nrow(distinct(df, NeedHouseholdId))
  
  all_for_shelter <- nrow(distinct(df %>%
                                     filter(client_requested_shelter == "Yes")
                                   , NeedHouseholdId))
  
  families <- nrow(distinct(df %>%
                              filter(min_age < 18)
                            , NeedHouseholdId))
  
  families_for_shelter <- nrow(distinct(df %>%
                                          filter(min_age < 18 &
                                                   client_requested_shelter == "Yes")
                                        , NeedHouseholdId))
  
  veterans <- nrow(distinct(df %>%
                              filter(veteran == "Yes")
                            , ClientUid))
  
  veterans_for_shelter <- nrow(distinct(df %>%
                                          filter(veteran == "Yes" &
                                                   client_requested_shelter == "Yes")
                                        , ClientUid))
  
  youth <- nrow(distinct(df %>%
                           filter(max_age >= 18 &
                                    max_age <= 24)
                         , NeedHouseholdId))
  
  youth_for_shelter <- nrow(distinct(df %>%
                                       filter(max_age >= 18 &
                                                max_age <= 24 &
                                                client_requested_shelter == "Yes")
                                     , NeedHouseholdId))
  
  seniors <- nrow(distinct(df %>%
                             filter(Age >= 55)
                           , ClientUid))
  
  seniors_for_shelter <- nrow(distinct(df %>%
                                         filter(Age >= 55 &
                                                  client_requested_shelter == "Yes")
                                       , ClientUid))
  
  BIPOC <- nrow(distinct(df %>%
                           filter((max_age >= 18 |
                                     is.na(max_age)) &
                                    BIPOC_flag == 1)
                         , NeedHouseholdId))
  
  BIPOC_for_shelter <- nrow(distinct(df %>%
                                       filter((max_age >= 18 |
                                                 is.na(max_age)) &
                                                BIPOC_flag == 1 &
                                                client_requested_shelter == "Yes")
                                     , NeedHouseholdId))
  
  cat("\n", title,
      "\nAll households calling: ", paste0(all_calling),
      "\nAll households calling for shelter: ", paste0(all_for_shelter),
      "\nFamilies calling: ", paste0(families),
      "\nFamilies calling for shelter: ", paste0(families_for_shelter),
      "\nVeterans calling: ", paste0(veterans),
      "\nVeterans calling for shelter: ", paste0(veterans_for_shelter),
      "\nYouth households calling: ", paste0(youth),
      "\nYouth households calling for shelter: ", paste0(youth_for_shelter),
      "\nSeniors calling: ", paste0(seniors),
      "\nSeniors calling for shelter: ", paste0(seniors_for_shelter), 
      "\nBIPOC households calling: ", paste0(BIPOC),
      "\nBIPOC households calling for shelter: ", paste0(BIPOC_for_shelter), "\n")
}

```



```{r run hotline summary calculations}

hotline_summary_numbers(for_summary, "All Calling")

hotline_summary_numbers(for_summary %>%
                          filter(Housed_Status == "Literally Homeless")
                        , "Literally Homeless Calling")

hotline_summary_numbers(for_summary %>%
                          filter(Housed_Status != "Literally Homeless")
                        , "Not Homeless/Unknown Calling")

```
















