---
title: "Annual Entry Report"
author: "Laura Pelayo"
date: "2024-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(pander)
library(dplyr)
library(readr)
library(stringr)
library(readxl)
```

## Annual Entry Report

Runs on Program Dashboard data

```{r Read Data and initial cleaning}

# Set the report year dates
year_start <- ymd("20230101")
year_end <- ymd("20231231")
 
# Set the path to Program Dashboard
all_data <- "Data/Excel format/FY24 Program Dashboard.xlsx"

ee_during_period <- read_excel(all_data, sheet = 1) %>%
  `colnames<-`(gsub(" ", "", names(.))) %>%
  rename(ClientId = EntryExitClientId) %>%
  group_by(EntryExitGroupUID) %>%
  mutate(EntryExitExitDate = as.Date(EntryExitExitDate),
         max_entry_age = max(ClientAgeatEntry),
         min_entry_age = min(ClientAgeatEntry),
         VARCreatedHouseholdID = gsub(",", "", VARCreatedHouseholdID)) %>%
  ungroup()

demographic_data <- read_excel(all_data, sheet = 2) %>%
  `colnames<-`(gsub(" ", "", names(.))) %>%
  rename(ClientId = ClientUid) %>%
  arrange(desc(MostRecentAssessmentScore)) %>%
  group_by(ClientId) %>%
  slice(1L) %>%
  ungroup()

program_data <- read_excel(all_data, sheet = 3) %>%
  `colnames<-`(gsub(" ", "", names(.)))


```


```{r Get Column names}

# Print all column names to check the structure
cat("Column names for ee_during_period:\n")
cat(paste(colnames(ee_during_period), collapse = "\n"), "\n\n") 
cat("Column names for demographic_data:\n")
cat(paste(colnames(demographic_data), collapse = "\n"), "\n\n") 
cat("Column names for program_data:\n")
cat(paste(colnames(program_data), collapse = "\n"), "\n\n")

```




```{r system map}

system_map_numbers <- function(df, column, title)
  
{
  entered_shelter <- nrow(distinct(df %>%
                                     filter(EntryExitProviderProgramTypeCode == "Emergency Shelter - Entry Exit (HUD)" &
                                              EntryExitEntryDate >= year_start &
                                              EntryExitEntryDate <= year_end)
                                   , !!column))
  entered_diversion <- nrow(distinct(df %>%
                                     filter(EntryExitProviderProgramTypeCode == "Diversion" &
                                              EntryExitEntryDate >= year_start &
                                              EntryExitEntryDate <= year_end)
                                   , !!column))
  diverted <- nrow(distinct(df %>%
                                     filter(EntryExitProviderProgramTypeCode == "Diversion" &
                                              ExitDestinationType == "Permanent Situation" &
                                              EntryExitExitDate >= year_start &
                                              EntryExitExitDate <= year_end)
                                   , !!column))
# Filter and count distinct households open at any point in 2023
in_ce <- nrow(distinct(df %>%
                        filter(EntryExitProviderProgramTypeCode == "Coordinated Entry (HUD)" &
                               ((EntryExitEntryDate < year_start & (is.na(EntryExitExitDate) | EntryExitExitDate >= year_start)) |
                                (EntryExitEntryDate >= year_start & EntryExitEntryDate <= year_end)))
                      , !!column))
  
  entered_housing_program <- nrow(distinct(df %>%
                                     filter(EntryExitProviderProgramTypeCode %in% c("Transitional housing (HUD)",
                                                                                    "PH - Rapid Re-Housing (HUD)",
                                                                                    "PH - Permanent Supportive Housing (disability required for entry) (HUD)") &
                                              EntryExitEntryDate >= year_start &
                                              EntryExitEntryDate <= year_end)
                                   , !!column))
  homelessness_prevented <- nrow(distinct(df %>%
                              filter(EntryExitProviderProgramTypeCode == "Homelessness Prevention (HUD)" &
                                       ExitDestinationType == "Permanent Situation" &
                                       EntryExitExitDate >= year_start &
                                       EntryExitExitDate <= year_end)
                            , !!column))
  
  cat("\n", title,
      "\nEntered shelter: ", paste0(entered_shelter),
      "\nEntered diversion: ", paste0(entered_diversion),
      "\nHoused through diversion: ", paste0(diverted),
      "\nWere open in CE: ", paste0(in_ce),
      "\nEntered TH/RRH/PSH program: ", paste0(entered_housing_program),
      "\nStabilized through prevention: ", paste0(homelessness_prevented), "\n")
}

```



```{r run system numbers}

system_map_numbers(ee_during_period, quo(VARCreatedHouseholdID), "All Households")

system_map_numbers(ee_during_period %>%
                     filter(min_entry_age < 18)
                   , quo(VARCreatedHouseholdID), "Families With Children")

system_map_numbers(ee_during_period %>%
                     inner_join(demographic_data %>%
                                  filter(VeteranStatus == "Yes (HUD)"),
                                by = "ClientId")
                   , quo(ClientId), "Veterans")

system_map_numbers(ee_during_period %>%
                     filter(max_entry_age >= 18 &
                              max_entry_age <= 24)
                   , quo(VARCreatedHouseholdID), "Youth Households")

system_map_numbers(ee_during_period %>%
                     filter(ClientAgeatEntry >= 55)
                   , quo(ClientId), "Seniors 55+")

system_map_numbers(
  ee_during_period %>%
    filter(ClientAgeatEntry >= 18) %>%
    inner_join(
      demographic_data %>%
        filter(
          str_detect(`RaceandEthnicity(3397)`, "American Indian, Alaska Native, or Indigenous") |
          str_detect(`RaceandEthnicity(3397)`, "Asian or Asian American") |
          str_detect(`RaceandEthnicity(3397)`, "Black, African American, or African") |
          str_detect(`RaceandEthnicity(3397)`, "Hispanic/Latina/e/o") |
          str_detect(`RaceandEthnicity(3397)`, "Middle Eastern or North African") |
          str_detect(`RaceandEthnicity(3397)`, "Native Hawaiian or Pacific Islander")
        ), 
      by = "ClientId"
    ),
  quo(VARCreatedHouseholdID), 
  "BIPOC Households"
)

```


```{r get program numbers}

housing_program_entries <- ee_during_period %>%
  filter(EntryExitProviderProgramTypeCode %in% c("Transitional housing (HUD)",
                                                 "PH - Rapid Re-Housing (HUD)",
                                                 "PH - Permanent Supportive Housing (disability required for entry) (HUD)") &
           EntryExitEntryDate >= year_start &
           EntryExitEntryDate <= year_end) %>%
  left_join(program_data %>%
              select(Agency, Provider) %>%
              distinct(), 
            by = c("EntryExitProviderId" = "Provider"))

agency_count <- nrow(distinct(housing_program_entries, Agency))
program_count <- nrow(distinct(housing_program_entries, EntryExitProviderId))
household_count <- nrow(distinct(housing_program_entries, VARCreatedHouseholdID))  ## this will match number from above

cat(paste0(agency_count), "agencies administered", paste0(program_count),
    "programs that entered", paste0(household_count), "households in 2023.")

housing_program_types <- housing_program_entries %>%
  select(EntryExitProviderId, EntryExitProviderProgramTypeCode) %>%
  distinct() %>%
  group_by(EntryExitProviderProgramTypeCode) %>%
  summarise(programs = n())

```






























